### ISSUE TITLE
curl: command not found

### ISSUE THREAD

**Issue by mursts** [keima/step-go-appengine-util#2]
It failed with deploy.
curl is not found. It seems there is a need to install the curl.
I'm sorry if I use the wrong.

wercker output

```
/pipeline/go-appengine-util-d4b9c507-3d16-4ed9-9467-75ab51388bbb/run.sh: line 105: curl: command not found
latest: 
check_update is failed. Probably using in-cache SDK.
failed: $LATEST is empty
```

wercker.yml

```
deploy:
  steps:
    - keima/go-appengine-util@0.2.4:
        method: deploy
        gopath: $WERCKER_SOURCE_DIR
        token: $APP_ENGINE_TOKEN
```

**Comment by keima** [comment]
Thanks for reporting issue!

Please tell me more information.
- value of box: attribution of wercker.yml
  - e.g. box: node:5.10

---

In fact, go-appengine-util is depends on curl command.
So it's not check whether curl is exists or not.

In other words, we should use wercker box (docker container) including curl command.
(Most of Ubuntu-based containers has curl command.)

**Comment by mursts** [comment]
Thank you for replying.

my wercker.yml

```
box: debian
build:
  steps:
    - arjen/hugo-build:
        flags: --buildDrafts=false
deploy:
  steps:
    - keima/go-appengine-util@0.2.4:
        method: deploy
        gopath: $WERCKER_SOURCE_DIR
        token: $APP_ENGINE_TOKEN
```

I tried other box

| box | result |
| --- | --- |
| debian | NG |
| ubuntu | NG |
| node | OK |
| centos | NG |

also centos is 7z not found

output

```
/pipeline/go-appengine-util-8552fd0c-c6d6-4ddd-9010-bec42a263398/run.sh: line 87: hash: 7z: not found
7z is not found.
failed: [install_deps_if_needed] failed. Show output log.
```
